import React, { useState } from "react";
import logos from "../../assets/AddressFill.svg";
import Select from "react-select";

function AddressFill() {
 const [selectedCountry, setSelectedCountry] = useState({
  value: "IN",
  label: "India"
 });
 const [selectedState, setSelectedState] = useState(null);
 const [selectedCity, setSelectedCity] = useState(null);
 const [cityOptions, setCityOptions] = useState([]);
 const [stateOptions, setStateOptions] = useState([]);

 const indiaStates = [
  { value: "AP", label: "Andhra Pradesh" },
  { value: "AR", label: "Arunachal Pradesh" },
  { value: "AS", label: "Assam" },
  { value: "BR", label: "Bihar" },
  { value: "CT", label: "Chhattisgarh" },
  { value: "GA", label: "Goa" },
  { value: "GJ", label: "Gujarat" },
  { value: "HR", label: "Haryana" },
  { value: "HP", label: "Himachal Pradesh" },
  { value: "JK", label: "Jammu and Kashmir" },
  { value: "JH", label: "Jharkhand" },
  { value: "KA", label: "Karnataka" },
  { value: "KL", label: "Kerala" },
  { value: "MP", label: "Madhya Pradesh" },
  { value: "MH", label: "Maharashtra" },
  { value: "MN", label: "Manipur" },
  { value: "ML", label: "Meghalaya" },
  { value: "MZ", label: "Mizoram" },
  { value: "NL", label: "Nagaland" },
  { value: "OR", label: "Odisha" },
  { value: "PB", label: "Punjab" },
  { value: "RJ", label: "Rajasthan" },
  { value: "SK", label: "Sikkim" },
  { value: "TN", label: "Tamil Nadu" },
  { value: "TG", label: "Telangana" },
  { value: "TR", label: "Tripura" },
  { value: "UP", label: "Uttar Pradesh" },
  { value: "UT", label: "Uttarakhand" },
  { value: "WB", label: "West Bengal" },
  // Union Territories
  { value: "AN", label: "Andaman and Nicobar Islands" },
  { value: "CH", label: "Chandigarh" },
  { value: "DN", label: "Dadra and Nagar Haveli and Daman and Diu" },
  { value: "LD", label: "Lakshadweep" },
  { value: "DL", label: "Delhi" },
  { value: "PY", label: "Puducherry" },
  { value: "LA", label: "Ladakh" },
  { value: "JK", label: "Jammu and Kashmir" }
 ];

 const stateDistricts = {
  AP: [
   { value: "anantapur", label: "Anantapur" },
   { value: "chittoor", label: "Chittoor" },
   { value: "east-godavari", label: "East Godavari" },
   { value: "guntur", label: "Guntur" },
   { value: "krishna", label: "Krishna" },
   { value: "kurnool", label: "Kurnool" },
   { value: "prakasam", label: "Prakasam" },
   { value: "spsr-nellore", label: "S.P.S. Nellore" },
   { value: "srikakulam", label: "Srikakulam" },
   { value: "visakhapatnam", label: "Visakhapatnam" },
   { value: "vizianagaram", label: "Vizianagaram" },
   { value: "west-godavari", label: "West Godavari" },
   { value: "ysr-kadapa", label: "Y.S.R. Kadapa" }
  ],
  AR: [
   { value: "tawang", label: "Tawang" },
   { value: "west-kameng", label: "West Kameng" },
   { value: "east-kameng", label: "East Kameng" },
   { value: "papum-pare", label: "Papum Pare" },
   { value: "kurung-kumey", label: "Kurung Kumey" },
   { value: "kra-daadi", label: "Kra Daadi" },
   { value: "lower-subansiri", label: "Lower Subansiri" },
   { value: "upper-subansiri", label: "Upper Subansiri" },
   { value: "west-siang", label: "West Siang" },
   { value: "east-siang", label: "East Siang" },
   { value: "siang", label: "Siang" },
   { value: "upper-siang", label: "Upper Siang" },
   { value: "lower-siang", label: "Lower Siang" },
   { value: "lower-dibang-valley", label: "Lower Dibang Valley" },
   { value: "dibang-valley", label: "Dibang Valley" },
   { value: "anjaw", label: "Anjaw" },
   { value: "lohit", label: "Lohit" },
   { value: "namsai", label: "Namsai" },
   { value: "changlang", label: "Changlang" },
   { value: "tirap", label: "Tirap" },
   { value: "longding", label: "Longding" }
  ],
  AS: [
   { value: "baksa", label: "Baksa" },
   { value: "barpeta", label: "Barpeta" },
   { value: "biswanath", label: "Biswanath" },
   { value: "bongaigaon", label: "Bongaigaon" },
   { value: "cachar", label: "Cachar" },
   { value: "charaideo", label: "Charaideo" },
   { value: "chirang", label: "Chirang" },
   { value: "darrang", label: "Darrang" },
   { value: "dhemaji", label: "Dhemaji" },
   { value: "dhubri", label: "Dhubri" },
   { value: "dibrugarh", label: "Dibrugarh" },
   { value: "dima-hasao", label: "Dima Hasao" },
   { value: "goalpara", label: "Goalpara" },
   { value: "golaghat", label: "Golaghat" },
   { value: "hailakandi", label: "Hailakandi" },
   { value: "hojai", label: "Hojai" },
   { value: "jorhat", label: "Jorhat" },
   { value: "kamrup-metro", label: "Kamrup Metropolitan" },
   { value: "kamrup", label: "Kamrup" },
   { value: "karbi-anglong", label: "Karbi Anglong" },
   { value: "karimganj", label: "Karimganj" },
   { value: "kokrajhar", label: "Kokrajhar" },
   { value: "lakhimpur", label: "Lakhimpur" },
   { value: "majuli", label: "Majuli" },
   { value: "morigaon", label: "Morigaon" },
   { value: "nagaon", label: "Nagaon" },
   { value: "nalbari", label: "Nalbari" },
   { value: "sivasagar", label: "Sivasagar" },
   { value: "sonitpur", label: "Sonitpur" },
   { value: "south-salmara-mankachar", label: "South Salmara-Mankachar" },
   { value: "tinsukia", label: "Tinsukia" },
   { value: "udalguri", label: "Udalguri" },
   { value: "west-karbi-anglong", label: "West Karbi Anglong" }
  ],
  BR: [
   { value: "patna", label: "Patna" },
   { value: "gaya", label: "Gaya" },
   { value: "bhagalpur", label: "Bhagalpur" },
   { value: "muzaffarpur", label: "Muzaffarpur" },
   { value: "purnia", label: "Purnia" },
   { value: "darbhanga", label: "Darbhanga" },
   { value: "begusarai", label: "Begusarai" },
   { value: "chapra", label: "Chapra" },
   { value: "arraha", label: "Arraha" },
   { value: "buxar", label: "Buxar" },
   { value: "saharsa", label: "Saharsa" },
   { value: "sitamarhi", label: "Sitamarhi" },
   { value: "katihaar", label: "Katihaar" },
   { value: "munger", label: "Munger" },
   { value: "madhubani", label: "Madhubani" },
   { value: "samastipur", label: "Samastipur" },
   { value: "siwan", label: "Siwan" },
   { value: "purvi-champaran", label: "Purvi Champaran" },
   { value: "pashchim-champaran", label: "Pashchim Champaran" },
   { value: "nawada", label: "Nawada" },
   { value: "banka", label: "Banka" },
   { value: "supaul", label: "Supaul" },
   { value: "gopalganj", label: "Gopalganj" },
   { value: "khagaria", label: "Khagaria" },
   { value: "bhojpur", label: "Bhojpur" },
   { value: "madhepura", label: "Madhepura" },
   { value: "jamui", label: "Jamui" },
   { value: "jehanabad", label: "Jehanabad" },
   { value: "arwal", label: "Arwal" },
   { value: "sheikhpura", label: "Sheikhpura" },
   { value: "lakhisarai", label: "Lakhisarai" }
  ],
  CT: [
   { value: "bastar", label: "Bastar" },
   { value: "bijapur", label: "Bijapur" },
   { value: "bilaspur", label: "Bilaspur" },
   { value: "dantewada", label: "Dantewada" },
   { value: "dhamtari", label: "Dhamtari" },
   { value: "durg", label: "Durg" },
   { value: "janjgir-champa", label: "Janjgir-Champa" },
   { value: "jashpur", label: "Jashpur" },
   { value: "kanker", label: "Kanker" },
   { value: "kawardha", label: "Kawardha" },
   { value: "korba", label: "Korba" },
   { value: "koriya", label: "Koriya" },
   { value: "mahasamund", label: "Mahasamund" },
   { value: "raigarh", label: "Raigarh" },
   { value: "raipur", label: "Raipur" },
   { value: "rajnandgaon", label: "Rajnandgaon" },
   { value: "surguja", label: "Surguja" }
  ],
  GA: [
   { value: "north-goa", label: "North Goa" },
   { value: "south-goa", label: "South Goa" }
  ],
  GJ: [
   { value: "ahmedabad", label: "Ahmedabad" },
   { value: "amreli", label: "Amreli" },
   { value: "anand", label: "Anand" },
   { value: "aravalli", label: "Aravalli" },
   { value: "banaskantha", label: "Banaskantha" },
   { value: "bharuch", label: "Bharuch" },
   { value: "bhavnagar", label: "Bhavnagar" },
   { value: "botad", label: "Botad" },
   { value: "chhotaudepur", label: "Chhota Udepur" },
   { value: "devbhoomidwarka", label: "Devbhoomi Dwarka" },
   { value: "dohad", label: "Dohad" },
   { value: "gandhinagar", label: "Gandhinagar" },
   { value: "gir-somnath", label: "Gir Somnath" },
   { value: "jamnagar", label: "Jamnagar" },
   { value: "junagadh", label: "Junagadh" },
   { value: "kachchh", label: "Kachchh" },
   { value: "kheda", label: "Kheda" },
   { value: "mahesana", label: "Mahesana" },
   { value: "mehsana", label: "Mehsana" },
   { value: "morbi", label: "Morbi" },
   { value: "narmada", label: "Narmada" },
   { value: "navsari", label: "Navsari" },
   { value: "panchmahal", label: "Panchmahal" },
   { value: "patan", label: "Patan" },
   { value: "porbandar", label: "Porbandar" },
   { value: "rajkot", label: "Rajkot" },
   { value: "sabarkantha", label: "Sabarkantha" },
   { value: "surat", label: "Surat" },
   { value: "surendranagar", label: "Surendranagar" },
   { value: "tapi", label: "Tapi" },
   { value: "vadodara", label: "Vadodara" },
   { value: "valsad", label: "Valsad" }
  ],
  HR: [
   { value: "ambala", label: "Ambala" },
   { value: "bhiwani", label: "Bhiwani" },
   { value: "charkhidadri", label: "Charkhi Dadri" },
   { value: "faridabad", label: "Faridabad" },
   { value: "fatehabad", label: "Fatehabad" },
   { value: "gurugram", label: "Gurugram" },
   { value: "hisar", label: "Hisar" },
   { value: "jhajjar", label: "Jhajjar" },
   { value: "jind", label: "Jind" },
   { value: "kaithal", label: "Kaithal" },
   { value: "karnal", label: "Karnal" },
   { value: "kurukshetra", label: "Kurukshetra" },
   { value: "mahendragarh", label: "Mahendragarh" },
   { value: "nuh", label: "Nuh" },
   { value: "palwal", label: "Palwal" },
   { value: "panchkula", label: "Panchkula" },
   { value: "panipat", label: "Panipat" },
   { value: "rewari", label: "Rewari" },
   { value: "rohtak", label: "Rohtak" },
   { value: "sirsa", label: "Sirsa" },
   { value: "sonipat", label: "Sonipat" },
   { value: "yamunanagar", label: "Yamunanagar" }
  ],
  HP: [
   { value: "bilaspur", label: "Bilaspur" },
   { value: "chamba", label: "Chamba" },
   { value: "hamirpur", label: "Hamirpur" },
   { value: "kangra", label: "Kangra" },
   { value: "kinnaur", label: "Kinnaur" },
   { value: "kullu", label: "Kullu" },
   { value: "lahaul-and-spiti", label: "Lahaul and Spiti" },
   { value: "mandi", label: "Mandi" },
   { value: "shimla", label: "Shimla" },
   { value: "sirmaur", label: "Sirmaur" },
   { value: "solan", label: "Solan" },
   { value: "una", label: "Una" }
  ],
  JH: [
   { value: "bokaro", label: "Bokaro" },
   { value: "chatra", label: "Chatra" },
   { value: "deoghar", label: "Deoghar" },
   { value: "dhanbad", label: "Dhanbad" },
   { value: "dumka", label: "Dumka" },
   { value: "east-singhbhum", label: "East Singhbhum" },
   { value: "garhwa", label: "Garhwa" },
   { value: "giridih", label: "Giridih" },
   { value: "godda", label: "Godda" },
   { value: "gumla", label: "Gumla" },
   { value: "hazaribagh", label: "Hazaribagh" },
   { value: "jamtara", label: "Jamtara" },
   { value: "khunti", label: "Khunti" },
   { value: "koderma", label: "Koderma" },
   { value: "latehar", label: "Latehar" },
   { value: "lohardaga", label: "Lohardaga" },
   { value: "pakur", label: "Pakur" },
   { value: "palamu", label: "Palamu" },
   { value: "ramgarh", label: "Ramgarh" },
   { value: "ranchi", label: "Ranchi" },
   { value: "sahibganj", label: "Sahibganj" },
   { value: "seraikela-kharsawan", label: "Seraikela Kharsawan" },
   { value: "simdega", label: "Simdega" },
   { value: "west-singhbhum", label: "West Singhbhum" }
  ],
  KA: [
   { value: "bagalkot", label: "Bagalkot" },
   { value: "ballari", label: "Ballari" },
   { value: "belagavi", label: "Belagavi" },
   { value: "bengaluru-rural", label: "Bengaluru Rural" },
   { value: "bengaluru-urban", label: "Bengaluru Urban" },
   { value: "bidar", label: "Bidar" },
   { value: "chamarajanagar", label: "Chamarajanagar" },
   { value: "chikballapur", label: "Chikballapur" },
   { value: "chikkamagaluru", label: "Chikkamagaluru" },
   { value: "chitradurga", label: "Chitradurga" },
   { value: "dakshina-kannada", label: "Dakshina Kannada" },
   { value: "davanagere", label: "Davanagere" },
   { value: "dharwad", label: "Dharwad" },
   { value: "gadag", label: "Gadag" },
   { value: "hassan", label: "Hassan" },
   { value: "haveri", label: "Haveri" },
   { value: "kalaburagi", label: "Kalaburagi" },
   { value: "kodagu", label: "Kodagu" },
   { value: "kolar", label: "Kolar" },
   { value: "koppal", label: "Koppal" },
   { value: "mandya", label: "Mandya" },
   { value: "mysuru", label: "Mysuru" },
   { value: "raichur", label: "Raichur" },
   { value: "ramanagara", label: "Ramanagara" },
   { value: "shivamogga", label: "Shivamogga" },
   { value: "tumakuru", label: "Tumakuru" },
   { value: "udupi", label: "Udupi" },
   { value: "uttara-kannada", label: "Uttara Kannada" },
   { value: "vijayapura", label: "Vijayapura" },
   { value: "yadgir", label: "Yadgir" }
  ],
  KL: [
   { value: "alappuzha", label: "Alappuzha" },
   { value: "ernakulam", label: "Ernakulam" },
   { value: "idukki", label: "Idukki" },
   { value: "kannur", label: "Kannur" },
   { value: "kasaragod", label: "Kasaragod" },
   { value: "kollam", label: "Kollam" },
   { value: "kottayam", label: "Kottayam" },
   { value: "kozhikode", label: "Kozhikode" },
   { value: "malappuram", label: "Malappuram" },
   { value: "palakkad", label: "Palakkad" },
   { value: "pathanamthitta", label: "Pathanamthitta" },
   { value: "thiruvananthapuram", label: "Thiruvananthapuram" },
   { value: "thrissur", label: "Thrissur" },
   { value: "wayanad", label: "Wayanad" }
  ],
  MP: [
   { value: "agar-malwa", label: "Agar Malwa" },
   { value: "alirajpur", label: "Alirajpur" },
   { value: "anuppur", label: "Anuppur" },
   { value: "ashoknagar", label: "Ashoknagar" },
   { value: "balaghat", label: "Balaghat" },
   { value: "barwani", label: "Barwani" },
   { value: "betul", label: "Betul" },
   { value: "bhind", label: "Bhind" },
   { value: "bhopal", label: "Bhopal" },
   { value: "burhanpur", label: "Burhanpur" },
   { value: "chhatarpur", label: "Chhatarpur" },
   { value: "chhindwara", label: "Chhindwara" },
   { value: "damoh", label: "Damoh" },
   { value: "datia", label: "Datia" },
   { value: "dewas", label: "Dewas" },
   { value: "dhar", label: "Dhar" },
   { value: "dindori", label: "Dindori" },
   { value: "guna", label: "Guna" },
   { value: "gwalior", label: "Gwalior" },
   { value: "harda", label: "Harda" },
   { value: "hoshangabad", label: "Hoshangabad" },
   { value: "indore", label: "Indore" },
   { value: "jabalpur", label: "Jabalpur" },
   { value: "jhabua", label: "Jhabua" },
   { value: "katni", label: "Katni" },
   { value: "khandwa", label: "Khandwa" },
   { value: "khargone", label: "Khargone" },
   { value: "mandla", label: "Mandla" },
   { value: "mandsaur", label: "Mandsaur" },
   { value: "morena", label: "Morena" },
   { value: "narsinghpur", label: "Narsinghpur" },
   { value: "neemuch", label: "Neemuch" },
   { value: "panna", label: "Panna" },
   { value: "raisen", label: "Raisen" },
   { value: "rajgarh", label: "Rajgarh" },
   { value: "ratlam", label: "Ratlam" },
   { value: "rewa", label: "Rewa" },
   { value: "sagar", label: "Sagar" },
   { value: "satna", label: "Satna" },
   { value: "sehore", label: "Sehore" },
   { value: "seoni", label: "Seoni" },
   { value: "shahdol", label: "Shahdol" },
   { value: "shajapur", label: "Shajapur" },
   { value: "sheopur", label: "Sheopur" },
   { value: "shivpuri", label: "Shivpuri" },
   { value: "sidhi", label: "Sidhi" },
   { value: "singrauli", label: "Singrauli" },
   { value: "tikamgarh", label: "Tikamgarh" },
   { value: "ujjain", label: "Ujjain" },
   { value: "umaria", label: "Umaria" },
   { value: "vidisha", label: "Vidisha" }
  ],
  MH: [
   { value: "ahmednagar", label: "Ahmednagar" },
   { value: "akola", label: "Akola" },
   { value: "amravati", label: "Amravati" },
   { value: "aurangabad", label: "Aurangabad" },
   { value: "beed", label: "Beed" },
   { value: "bhandara", label: "Bhandara" },
   { value: "buldhana", label: "Buldhana" },
   { value: "chandrapur", label: "Chandrapur" },
   { value: "dhule", label: "Dhule" },
   { value: "gadchiroli", label: "Gadchiroli" },
   { value: "gondia", label: "Gondia" },
   { value: "hingoli", label: "Hingoli" },
   { value: "jalgaon", label: "Jalgaon" },
   { value: "jalna", label: "Jalna" },
   { value: "kolhapur", label: "Kolhapur" },
   { value: "latur", label: "Latur" },
   { value: "mumbai-city", label: "Mumbai City" },
   { value: "mumbai-suburban", label: "Mumbai Suburban" },
   { value: "nagpur", label: "Nagpur" },
   { value: "nanded", label: "Nanded" },
   { value: "nandurbar", label: "Nandurbar" },
   { value: "nashik", label: "Nashik" },
   { value: "osmanabad", label: "Osmanabad" },
   { value: "palghar", label: "Palghar" },
   { value: "parbhani", label: "Parbhani" },
   { value: "pune", label: "Pune" },
   { value: "raigad", label: "Raigad" },
   { value: "ratnagiri", label: "Ratnagiri" },
   { value: "sangli", label: "Sangli" },
   { value: "satara", label: "Satara" },
   { value: "sindhudurg", label: "Sindhudurg" },
   { value: "solapur", label: "Solapur" },
   { value: "thane", label: "Thane" },
   { value: "wardha", label: "Wardha" },
   { value: "washim", label: "Washim" },
   { value: "yavatmal", label: "Yavatmal" }
  ],
  MN: [
   { value: "bishnupur", label: "Bishnupur" },
   { value: "chandel", label: "Chandel" },
   { value: "churachandpur", label: "Churachandpur" },
   { value: "imphal-east", label: "Imphal East" },
   { value: "imphal-west", label: "Imphal West" },
   { value: "jiribam", label: "Jiribam" },
   { value: "kakching", label: "Kakching" },
   { value: "kamjong", label: "Kamjong" },
   { value: "kangpokpi", label: "Kangpokpi" },
   { value: "noney", label: "Noney" },
   { value: "pherzawl", label: "Pherzawl" },
   { value: "senapati", label: "Senapati" },
   { value: "tamenglong", label: "Tamenglong" },
   { value: "tengnoupal", label: "Tengnoupal" },
   { value: "thoubal", label: "Thoubal" },
   { value: "ukhrul", label: "Ukhrul" }
  ],
  ML: [
   { value: "east-garo-hills", label: "East Garo Hills" },
   { value: "east-jaintia-hills", label: "East Jaintia Hills" },
   { value: "east-khasi-hills", label: "East Khasi Hills" },
   { value: "north-garo-hills", label: "North Garo Hills" },
   { value: "ri-bhoi", label: "Ri-Bhoi" },
   { value: "south-garo-hills", label: "South Garo Hills" },
   { value: "south-west-garo-hills", label: "South West Garo Hills" },
   { value: "south-west-khasi-hills", label: "South West Khasi Hills" },
   { value: "west-garo-hills", label: "West Garo Hills" },
   { value: "west-jaintia-hills", label: "West Jaintia Hills" },
   { value: "west-khasi-hills", label: "West Khasi Hills" }
  ],
  MZ: [
   { value: "aizawl", label: "Aizawl" },
   { value: "champhai", label: "Champhai" },
   { value: "kolasib", label: "Kolasib" },
   { value: "lawngtlai", label: "Lawngtlai" },
   { value: "lunglei", label: "Lunglei" },
   { value: "mamit", label: "Mamit" },
   { value: "serchhip", label: "Serchhip" },
   { value: "siaha", label: "Siaha" }
  ],
  NL: [
   { value: "dimapur", label: "Dimapur" },
   { value: "kiphire", label: "Kiphire" },
   { value: "kohima", label: "Kohima" },
   { value: "longleng", label: "Longleng" },
   { value: "mokokchung", label: "Mokokchung" },
   { value: "mon", label: "Mon" },
   { value: "peren", label: "Peren" },
   { value: "phek", label: "Phek" },
   { value: "tuensang", label: "Tuensang" },
   { value: "wokha", label: "Wokha" },
   { value: "zunheboto", label: "Zunheboto" }
  ],
  OR: [
   { value: "angul", label: "Angul" },
   { value: "balangir", label: "Balangir" },
   { value: "balasore", label: "Balasore" },
   { value: "bargarh", label: "Bargarh" },
   { value: "bhadrak", label: "Bhadrak" },
   { value: "boudh", label: "Boudh" },
   { value: "cuttack", label: "Cuttack" },
   { value: "deogarh", label: "Deogarh" },
   { value: "dhenkanal", label: "Dhenkanal" },
   { value: "gajapati", label: "Gajapati" },
   { value: "ganjam", label: "Ganjam" },
   { value: "jagatsinghpur", label: "Jagatsinghpur" },
   { value: "jajpur", label: "Jajpur" },
   { value: "jharsuguda", label: "Jharsuguda" },
   { value: "kalahandi", label: "Kalahandi" },
   { value: "kandhamal", label: "Kandhamal" },
   { value: "kendrapara", label: "Kendrapara" },
   { value: "kendujhar", label: "Kendujhar" },
   { value: "khordha", label: "Khordha" },
   { value: "koraput", label: "Koraput" },
   { value: "malkangiri", label: "Malkangiri" },
   { value: "mayurbhanj", label: "Mayurbhanj" },
   { value: "nabarangpur", label: "Nabarangpur" },
   { value: "nayagarh", label: "Nayagarh" },
   { value: "nuapada", label: "Nuapada" },
   { value: "puri", label: "Puri" },
   { value: "rayagada", label: "Rayagada" },
   { value: "sambalpur", label: "Sambalpur" },
   { value: "subarnapur", label: "Subarnapur" },
   { value: "sundargarh", label: "Sundargarh" }
  ],
  PB: [
   { value: "amritsar", label: "Amritsar" },
   { value: "barnala", label: "Barnala" },
   { value: "bathinda", label: "Bathinda" },
   { value: "faridkot", label: "Faridkot" },
   { value: "fatehgarh-sahib", label: "Fatehgarh Sahib" },
   { value: "fazilka", label: "Fazilka" },
   { value: "ferozepur", label: "Ferozepur" },
   { value: "gurdaspur", label: "Gurdaspur" },
   { value: "hoshiarpur", label: "Hoshiarpur" },
   { value: "jalandhar", label: "Jalandhar" },
   { value: "kapurthala", label: "Kapurthala" },
   { value: "ludhiana", label: "Ludhiana" },
   { value: "mansa", label: "Mansa" },
   { value: "moga", label: "Moga" },
   { value: "muktsar", label: "Muktsar" },
   { value: "pathankot", label: "Pathankot" },
   { value: "patiala", label: "Patiala" },
   { value: "rupnagar", label: "Rupnagar" },
   { value: "sahibzada-ajit-singh-nagar", label: "Sahibzada Ajit Singh Nagar" },
   { value: "sangrur", label: "Sangrur" },
   { value: "tarn-taran", label: "Tarn Taran" }
  ],
  RJ: [
   { value: "ajmer", label: "Ajmer" },
   { value: "alwar", label: "Alwar" },
   { value: "banswara", label: "Banswara" },
   { value: "baran", label: "Baran" },
   { value: "barmer", label: "Barmer" },
   { value: "bharatpur", label: "Bharatpur" },
   { value: "bhilwara", label: "Bhilwara" },
   { value: "bikaner", label: "Bikaner" },
   { value: "bundi", label: "Bundi" },
   { value: "chittorgarh", label: "Chittorgarh" },
   { value: "churu", label: "Churu" },
   { value: "dausa", label: "Dausa" },
   { value: "dholpur", label: "Dholpur" },
   { value: "dungarpur", label: "Dungarpur" },
   { value: "hanumangarh", label: "Hanumangarh" },
   { value: "jaipur", label: "Jaipur" },
   { value: "jaisalmer", label: "Jaisalmer" },
   { value: "jalore", label: "Jalore" },
   { value: "jhalawar", label: "Jhalawar" },
   { value: "jhunjhunu", label: "Jhunjhunu" },
   { value: "jodhpur", label: "Jodhpur" },
   { value: "karauli", label: "Karauli" },
   { value: "kota", label: "Kota" },
   { value: "nagaur", label: "Nagaur" },
   { value: "pali", label: "Pali" },
   { value: "pratapgarh", label: "Pratapgarh" },
   { value: "rajsamand", label: "Rajsamand" },
   { value: "sawai-madhopur", label: "Sawai Madhopur" },
   { value: "sikar", label: "Sikar" },
   { value: "sirohi", label: "Sirohi" },
   { value: "sri-ganganagar", label: "Sri Ganganagar" },
   { value: "tonk", label: "Tonk" },
   { value: "udaipur", label: "Udaipur" }
  ],
  SK: [
   { value: "east", label: "East" },
   { value: "north", label: "North" },
   { value: "south", label: "South" },
   { value: "west", label: "West" }
  ],
  TN: [
   { value: "ariyalur", label: "Ariyalur" },
   { value: "chennai", label: "Chennai" },
   { value: "coimbatore", label: "Coimbatore" },
   { value: "cuddalore", label: "Cuddalore" },
   { value: "dharmapuri", label: "Dharmapuri" },
   { value: "dindigul", label: "Dindigul" },
   { value: "erode", label: "Erode" },
   { value: "kanchipuram", label: "Kanchipuram" },
   { value: "kanyakumari", label: "Kanyakumari" },
   { value: "karur", label: "Karur" },
   { value: "krishnagiri", label: "Krishnagiri" },
   { value: "madurai", label: "Madurai" },
   { value: "nagapattinam", label: "Nagapattinam" },
   { value: "namakkal", label: "Namakkal" },
   { value: "nilgiris", label: "Nilgiris" },
   { value: "perambalur", label: "Perambalur" },
   { value: "pudukkottai", label: "Pudukkottai" },
   { value: "ramanathapuram", label: "Ramanathapuram" },
   { value: "salem", label: "Salem" },
   { value: "sivaganga", label: "Sivaganga" },
   { value: "thanjavur", label: "Thanjavur" },
   { value: "theni", label: "Theni" },
   { value: "thoothukudi", label: "Thoothukudi" },
   { value: "tiruchirappalli", label: "Tiruchirappalli" },
   { value: "tirunelveli", label: "Tirunelveli" },
   { value: "tiruppur", label: "Tiruppur" },
   { value: "tiruvallur", label: "Tiruvallur" },
   { value: "tiruvannamalai", label: "Tiruvannamalai" },
   { value: "tiruvarur", label: "Tiruvarur" },
   { value: "vellore", label: "Vellore" },
   { value: "viluppuram", label: "Viluppuram" },
   { value: "virudhunagar", label: "Virudhunagar" }
  ],
  TG: [
   { value: "adilabad", label: "Adilabad" },
   { value: "bhadradri-kothagudem", label: "Bhadradri Kothagudem" },
   { value: "hyderabad", label: "Hyderabad" },
   { value: "jagtial", label: "Jagtial" },
   { value: "jangaon", label: "Jangaon" },
   { value: "jayashankar-bhupalpally", label: "Jayashankar Bhupalpally" },
   { value: "jogulamba-gadwal", label: "Jogulamba Gadwal" },
   { value: "kamareddy", label: "Kamareddy" },
   { value: "karimnagar", label: "Karimnagar" },
   { value: "khammam", label: "Khammam" },
   { value: "komaram-bheem", label: "Komaram Bheem" },
   { value: "mahabubabad", label: "Mahabubabad" },
   { value: "mahbubnagar", label: "Mahbubnagar" },
   { value: "mancherial", label: "Mancherial" },
   { value: "medak", label: "Medak" },
   { value: "medchal-malkajgiri", label: "Medchal Malkajgiri" },
   { value: "nagarkurnool", label: "Nagarkurnool" },
   { value: "nalgonda", label: "Nalgonda" },
   { value: "nirmal", label: "Nirmal" },
   { value: "nizamabad", label: "Nizamabad" },
   { value: "peddapalli", label: "Peddapalli" },
   { value: "rajanna-sircilla", label: "Rajanna Sircilla" },
   { value: "ranga-reddy", label: "Ranga Reddy" },
   { value: "sangareddy", label: "Sangareddy" },
   { value: "siddipet", label: "Siddipet" },
   { value: "suryapet", label: "Suryapet" },
   { value: "vikarabad", label: "Vikarabad" },
   { value: "wanaparthy", label: "Wanaparthy" },
   { value: "warangal-rural", label: "Warangal Rural" },
   { value: "warangal-urban", label: "Warangal Urban" },
   { value: "yadadri-bhuvanagiri", label: "Yadadri Bhuvanagiri" }
  ],
  TR: [
   { value: "dhalai", label: "Dhalai" },
   { value: "gomati", label: "Gomati" },
   { value: "khowai", label: "Khowai" },
   { value: "north-tripura", label: "North Tripura" },
   { value: "sepahijala", label: "Sepahijala" },
   { value: "south-tripura", label: "South Tripura" },
   { value: "unakoti", label: "Unakoti" },
   { value: "west-tripura", label: "West Tripura" }
  ],
  UP: [
   { value: "agra", label: "Agra" },
   { value: "aligarh", label: "Aligarh" },
   { value: "allahabad", label: "Allahabad" },
   { value: "ambedkar-nagar", label: "Ambedkar Nagar" },
   { value: "amethi", label: "Amethi" },
   { value: "amroha", label: "Amroha" },
   { value: "auraiya", label: "Auraiya" },
   { value: "ayodhya", label: "Ayodhya" },
   { value: "azamgarh", label: "Azamgarh" },
   { value: "baghpat", label: "Baghpat" },
   { value: "bahraich", label: "Bahraich" },
   { value: "ballia", label: "Ballia" },
   { value: "balrampur", label: "Balrampur" },
   { value: "banda", label: "Banda" },
   { value: "barabanki", label: "Barabanki" },
   { value: "bareilly", label: "Bareilly" },
   { value: "basti", label: "Basti" },
   { value: "bhadohi", label: "Bhadohi" },
   { value: "bijnor", label: "Bijnor" },
   { value: "budaun", label: "Budaun" },
   { value: "bulandshahr", label: "Bulandshahr" },
   { value: "chandauli", label: "Chandauli" },
   { value: "chitrakoot", label: "Chitrakoot" },
   { value: "deoria", label: "Deoria" },
   { value: "etah", label: "Etah" },
   { value: "etawah", label: "Etawah" },
   { value: "farrukhabad", label: "Farrukhabad" },
   { value: "fatehpur", label: "Fatehpur" },
   { value: "firozabad", label: "Firozabad" },
   { value: "gautam-buddha-nagar", label: "Gautam Buddha Nagar" },
   { value: "ghaziabad", label: "Ghaziabad" },
   { value: "ghazipur", label: "Ghazipur" },
   { value: "gonda", label: "Gonda" },
   { value: "gorakhpur", label: "Gorakhpur" },
   { value: "hamirpur-up", label: "Hamirpur" },
   { value: "hapur", label: "Hapur" },
   { value: "hardoi", label: "Hardoi" },
   { value: "hathras", label: "Hathras" },
   { value: "jhansi", label: "Jhansi" },
   { value: "kannauj", label: "Kannauj" },
   { value: "kanpur-dehat", label: "Kanpur Dehat" },
   { value: "kanpur-nagar", label: "Kanpur Nagar" },
   { value: "kanshiram-nagar", label: "Kanshiram Nagar" },
   { value: "kaushambi", label: "Kaushambi" },
   { value: "kushinagar", label: "Kushinagar" },
   { value: "lakhimpur-kheri", label: "Lakhimpur Kheri" },
   { value: "lalitpur", label: "Lalitpur" },
   { value: "lucknow", label: "Lucknow" },
   { value: "maharajganj", label: "Maharajganj" },
   { value: "mahoba", label: "Mahoba" },
   { value: "mainpuri", label: "Mainpuri" },
   { value: "mathura", label: "Mathura" },
   { value: "mau", label: "Mau" },
   { value: "meerut", label: "Meerut" },
   { value: "mirzapur", label: "Mirzapur" },
   { value: "moradabad", label: "Moradabad" },
   { value: "muzaffarnagar", label: "Muzaffarnagar" },
   { value: "pilibhit", label: "Pilibhit" },
   { value: "pratapgarh-up", label: "Pratapgarh" },
   { value: "rae-bareli", label: "Rae Bareli" },
   { value: "rampur", label: "Rampur" },
   { value: "saharanpur", label: "Saharanpur" },
   { value: "sambhal", label: "Sambhal" },
   { value: "sant-kabir-nagar", label: "Sant Kabir Nagar" },
   { value: "shahjahanpur", label: "Shahjahanpur" },
   { value: "shamli", label: "Shamli" },
   { value: "shravasti", label: "Shravasti" },
   { value: "siddharthnagar", label: "Siddharthnagar" },
   { value: "sitapur", label: "Sitapur" },
   { value: "sonbhadra", label: "Sonbhadra" },
   { value: "sultanpur-up", label: "Sultanpur" },
   { value: "unnao", label: "Unnao" },
   { value: "varanasi", label: "Varanasi" }
  ],
  UT: [
   { value: "almora", label: "Almora" },
   { value: "bageshwar", label: "Bageshwar" },
   { value: "chamoli", label: "Chamoli" },
   { value: "champawat", label: "Champawat" },
   { value: "dehradun", label: "Dehradun" },
   { value: "haridwar", label: "Haridwar" },
   { value: "nainital", label: "Nainital" },
   { value: "pauri-garhwal", label: "Pauri Garhwal" },
   { value: "pithoragarh", label: "Pithoragarh" },
   { value: "rudraprayag", label: "Rudraprayag" },
   { value: "tehri-garhwal", label: "Tehri Garhwal" },
   { value: "udham-singh-nagar", label: "Udham Singh Nagar" },
   { value: "uttarkashi", label: "Uttarkashi" }
  ],
  WB: [
   { value: "alipurduar", label: "Alipurduar" },
   { value: "bankura", label: "Bankura" },
   { value: "birbhum", label: "Birbhum" },
   { value: "cooch-behar", label: "Cooch Behar" },
   { value: "dakshin-dinajpur", label: "Dakshin Dinajpur" },
   { value: "darjeeling", label: "Darjeeling" },
   { value: "hooghly", label: "Hooghly" },
   { value: "howrah", label: "Howrah" },
   { value: "jalpaiguri", label: "Jalpaiguri" },
   { value: "jhargram", label: "Jhargram" },
   { value: "kalimpong", label: "Kalimpong" },
   { value: "kolkata", label: "Kolkata" },
   { value: "malda", label: "Malda" },
   { value: "murshidabad", label: "Murshidabad" },
   { value: "nadia", label: "Nadia" },
   { value: "north-24-parganas", label: "North 24 Parganas" },
   { value: "paschim-bardhaman", label: "Paschim Bardhaman" },
   { value: "purba-bardhaman", label: "Purba Bardhaman" },
   { value: "purba-medinipur", label: "Purba Medinipur" },
   { value: "purulia", label: "Purulia" },
   { value: "south-24-parganas", label: "South 24 Parganas" },
   { value: "uttar-dinajpur", label: "Uttar Dinajpur" }
  ],
  AN: [
   { value: "north-and-middle-andaman", label: "North and Middle Andaman" },
   { value: "south-andaman", label: "South Andaman" },
   { value: "nicobar", label: "Nicobar" }
  ],
  CH: [{ value: "chandigarh", label: "Chandigarh" }],
  DN: [
   { value: "dadra-and-nagar-haveli", label: "Dadra and Nagar Haveli" },
   { value: "daman", label: "Daman" },
   { value: "diu", label: "Diu" }
  ],
  DL: [
   { value: "central-delhi", label: "Central Delhi" },
   { value: "east-delhi", label: "East Delhi" },
   { value: "new-delhi", label: "New Delhi" },
   { value: "north-delhi", label: "North Delhi" },
   { value: "north-east-delhi", label: "North East Delhi" },
   { value: "north-west-delhi", label: "North West Delhi" },
   { value: "shahdara", label: "Shahdara" },
   { value: "south-delhi", label: "South Delhi" },
   { value: "south-east-delhi", label: "South East Delhi" },
   { value: "south-west-delhi", label: "South West Delhi" },
   { value: "west-delhi", label: "West Delhi" }
  ],
  LD: [{ value: "lakshadweep", label: "Lakshadweep" }],
  LA: [
   { value: "kargil", label: "Kargil" },
   { value: "leh", label: "Leh" }
  ],
  PY: [
   { value: "karaikal", label: "Karaikal" },
   { value: "mahe", label: "Mahe" },
   { value: "puducherry", label: "Puducherry" },
   { value: "yanam", label: "Yanam" }
  ]
  // Add districts for other states as needed
 };

 const handleStateChange = (selectedOption) => {
  setSelectedState(selectedOption);
  setSelectedCity(null);
  setCityOptions(stateDistricts[selectedOption.value]);
 };

 const handleCityChange = (selectedOption) => {
  setSelectedCity(selectedOption);
 };

 return (
  <>
   <div className="main-div">
    <div className="svg-div">
     <img
      src={logos}
      alt="Error 404"
      style={{ width: "40rem", height: "50rem", marginTop: "50px" }}
     />
    </div>
    <div className="form-part-div">
     <h1 className="p1">Select Your Location</h1>
     <h2 className="p1" style={{ fontWeight: "300", fontSize: "1.6rem" }}>
      Illuminate the path to wellness with Doc Spotter's guiding light
     </h2>
     <div className="select-f1">
      <Select
       isClearable
       isSearchable
       className="select-country"
       classNamePrefix="select"
       options={[selectedCountry]}
       value={selectedCountry}
       onChange={() => {}}
       placeholder="Select Your Country"
       isDisabled
      />
     </div>
     <div className="select-f2">
      <Select
       isClearable
       isSearchable
       className="select-state"
       classNamePrefix="select"
       options={indiaStates}
       value={selectedState}
       onChange={handleStateChange}
       placeholder="Select Your State"
      />
      {selectedState && (
       <Select
        isClearable
        isSearchable
        className="select-city"
        classNamePrefix="select"
        options={cityOptions}
        value={selectedCity}
        onChange={handleCityChange}
        placeholder="Select Your District"
       />
      )}
     </div>
     <div
      className="btn-div"
      style={{ alignItems: "center", justifyContent: "center" }}
     >
      <div className="btn-div-1" style={{ marginRight: "50px" }}>
       <button type="submit" style={{ width: "300px" }}>
        Proceed
       </button>
      </div>
     </div>
    </div>
   </div>
  </>
 );
}

export default AddressFill;
